### PR TITLE
clarify where this package is going

### PR DESCRIPTION
**Pull request by sethladd**

### CODE REVIEW

**Comment by zoechi** [comment]
Thanks Seth, its definitely better.
Who would have thought that this causes so much confusion. I didn't have the impression that many people were using the elements anyway. Maybe many were just monitoring the progress.

**Comment by sabrooks** [comment]
Zoechi - I had just begun to use the elements (based on the example is Chris Storm's book).  The core elements were also instructive as examples of how to construct elements.

**Comment by zoechi** [comment]
You should be able to use the original JS core-elements like or almost like Dart Polymer elements. I suppose there is still some work to do to make this easy to use. I guess you read some repots on Chris' site about this too. I have no further details about planned next steps in this matter though.

**Comment by sabrooks** [comment]
Trying to implement that, but now the sample <click-counter> from the sample project won't work when compile to JS and view in Chrome.

**Pull request merged**
